"""Question models for Criador agent output and complete question records."""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class FocoInput(BaseModel):
    """Input data for a single foco (focus topic) from Excel.

    This model represents a single row from the input Excel file,
    containing the medical theme, specific focus, and target academic period.
    It serves as the starting point for the question generation pipeline.
    """

    # MANDATORY: Strict validation - no type coercion
    model_config = ConfigDict(strict=True)

    # Required fields - Portuguese domain terminology
    tema: str = Field(..., description="Tema médico (ex: Cardiologia)")
    foco: str = Field(
        ..., description="Foco específico dentro do tema (ex: Insuficiência Cardíaca)"
    )
    periodo: Literal["1º ano", "2º ano", "3º ano", "4º ano"] = Field(
        ...,
        description="Período acadêmico alvo (1º a 4º ano de medicina)",
    )

    @field_validator("periodo")
    @classmethod
    def validate_periodo(cls, v: str) -> str:
        """Validate periodo is one of the allowed academic periods.

        Args:
            v: The periodo value to validate

        Returns:
            The validated periodo value

        Raises:
            ValueError: If periodo is not in allowed values
        """
        allowed = ["1º ano", "2º ano", "3º ano", "4º ano"]
        if v not in allowed:
            raise ValueError(f"periodo must be one of {allowed}, got '{v}'")
        return v

    @field_validator("tema", "foco")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate string fields are non-empty and non-whitespace.

        Args:
            v: The string value to validate

        Returns:
            The stripped string value

        Raises:
            ValueError: If string is empty or whitespace-only
        """
        if not v or v.isspace():
            raise ValueError("Field cannot be empty or whitespace")
        return v.strip()


class SubFocoInput(FocoInput):
    """Input with generated sub-foco for question generation pipeline.

    Extends FocoInput with a specific sub-foco string generated by the
    SubFocoGenerator agent. Each SubFocoInput produces one question
    in the pipeline.
    """

    sub_foco: str = Field(
        ...,
        description="Sub-foco específico gerado pela IA ou fornecido manualmente",
    )

    @field_validator("sub_foco")
    @classmethod
    def validate_sub_foco_non_empty(cls, v: str) -> str:
        """Validate sub_foco is non-empty and non-whitespace.

        Args:
            v: The sub_foco value to validate

        Returns:
            The stripped sub_foco value

        Raises:
            ValueError: If sub_foco is empty or whitespace-only
        """
        if not v or v.isspace():
            raise ValueError("sub_foco cannot be empty or whitespace")
        return v.strip()


class CriadorOutput(BaseModel):
    """Output from question creator agent (Criador).

    This model represents the structured output from the Criador agent,
    containing the question statement, alternatives, correct answer,
    educational objective, difficulty level, and question type.
    """

    # MANDATORY: Strict validation - no type coercion
    model_config = ConfigDict(strict=True)

    # Required fields - Portuguese domain terminology
    enunciado: str = Field(..., description="Texto completo do enunciado da questão")
    alternativa_a: str = Field(..., description="Primeira alternativa")
    alternativa_b: str = Field(..., description="Segunda alternativa")
    alternativa_c: str = Field(..., description="Terceira alternativa")
    alternativa_d: str = Field(..., description="Quarta alternativa")
    resposta_correta: Literal["A", "B", "C", "D"] = Field(
        ...,
        description="Letra da resposta correta",
    )
    objetivo_educacional: str = Field(..., description="Objetivo pedagógico da questão")
    nivel_dificuldade: Literal[1, 2, 3] = Field(
        ...,
        description=(
            "Nível de dificuldade mapeado à Taxonomia de Bloom: "
            "1=Conhecimento/Compreensão (fácil), "
            "2=Aplicação/Análise (médio), "
            "3=Síntese/Avaliação (difícil)"
        ),
    )
    tipo_enunciado: str = Field(
        ...,
        description="Tipo do enunciado: conceitual, caso clínico, etc.",
    )


class QuestionRecord(BaseModel):
    """Complete question record with all 26 columns for Excel export.

    This model represents the final question record that will be exported
    to Excel, combining data from Criador, Comentador, and Validador agents,
    plus metadata and optional image support fields.
    """

    # MANDATORY: Strict validation - no type coercion
    model_config = ConfigDict(strict=True)

    # Base fields (4 columns)
    tema: str = Field(..., description="Tema médico da questão (ex: Gastroenterologia)")
    foco: str = Field(..., description="Foco específico dentro do tema (ex: Fígado)")
    sub_foco: str = Field(..., description="Sub-foco detalhado (ex: Funções hepáticas)")
    periodo: str = Field(..., description="Período do curso médico (1º ano, 2º ano, etc.)")

    # Question fields from CriadorOutput (7 columns)
    nivel_dificuldade: Literal[1, 2, 3] = Field(
        ...,
        description="Nível de dificuldade: 1=fácil, 2=médio, 3=difícil",
    )
    tipo_enunciado: str = Field(
        ...,
        description="Tipo do enunciado: conceitual, caso clínico, etc.",
    )
    enunciado: str = Field(..., description="Texto completo do enunciado da questão")
    alternativa_a: str = Field(..., description="Primeira alternativa")
    alternativa_b: str = Field(..., description="Segunda alternativa")
    alternativa_c: str = Field(..., description="Terceira alternativa")
    alternativa_d: str = Field(..., description="Quarta alternativa")
    resposta_correta: Literal["A", "B", "C", "D"] = Field(
        ...,
        description="Letra da resposta correta",
    )
    objetivo_educacional: str = Field(..., description="Objetivo pedagógico da questão")

    # Comment fields from ComentadorOutput (8 columns)
    comentario_introducao: str = Field(
        ...,
        description="Comentário introdutório contextualizando o tema",
    )
    comentario_visao_especifica: str = Field(
        ...,
        description="Análise específica do enunciado e contexto clínico",
    )
    comentario_alt_a: str = Field(
        ...,
        description="Comentário explicativo da alternativa A",
    )
    comentario_alt_b: str = Field(
        ...,
        description="Comentário explicativo da alternativa B",
    )
    comentario_alt_c: str = Field(
        ...,
        description="Comentário explicativo da alternativa C",
    )
    comentario_alt_d: str = Field(
        ...,
        description="Comentário explicativo da alternativa D",
    )
    comentario_visao_aprovado: str = Field(
        ...,
        description="Visão geral do aprovado com síntese final",
    )
    referencia_bibliografica: str = Field(
        ...,
        description="Fonte bibliográfica verificável obtida do Pinecone RAG",
    )

    # Image support fields - optional (2 columns)
    suporte_imagem: str | None = Field(
        default=None,
        description="Nome do arquivo de imagem de suporte (se aplicável)",
    )
    fonte_imagem: str | None = Field(
        default=None,
        description="Fonte ou crédito da imagem utilizada",
    )

    # Metadata fields (3 columns)
    modelo_llm: str = Field(
        ...,
        description="Modelo de LLM utilizado (ex: gpt-4, claude-sonnet-4.5)",
    )
    rodadas_validacao: int = Field(
        ...,
        ge=1,
        description="Número de rodadas de validação até aprovação/rejeição",
    )
    concordancia_comentador: bool = Field(
        ...,
        description="Se o comentador concordou com o gabarito declarado",
    )
